/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { BlogItem, MarketplaceProduct, CommunityPost } from './types';

export const TRANSLATIONS = {
  en: {
    appName: "NutriOS AI",
    tagline: "India's Health Super OS",
    onboardingTitle: "Transform Your Health with AI",
    getStarted: "Get Started",
    login: "Login / Sign Up",
    logout: "Log Out",
    welcome: "Welcome",
    streak: "Streak",
    days: "Days",
    coins: "NutriCoins",
    premium: "Premium",
    buyPremium: "Upgrade to NutriOS Gold",
    dashboard: "Dashboard",
    dietPlanner: "AI Diet Planner",
    groceryPlanner: "AI Grocery List",
    familyPlanner: "AI Family Nutri",
    recipeGenerator: "AI Recipe Builder",
    restaurantHelper: "AI Restaurant Swap",
    barcodeScanner: "AI Label Scanner",
    foodCamera: "AI Food Camera",
    waterReminder: "AI Water Tracker",
    medicineReminder: "AI Med Reminder",
    workoutPlan: "AI Trainer Workout",
    labAnalyzer: "AI Lab Report Expert",
    doctorChat: "AI Doctor Consultant",
    kidsGrowth: "Kids Growth",
    pregnancyTracker: "Pregnancy Track",
    seniorCare: "Senior Care Active",
    sleepTracker: "Sleep & Circadian",
    weightTracker: "Weight & Body Stats",
    subscription: "Subscriptions",
    affiliateMarket: "Health Store",
    adminPanel: "OS Control Panel",
    blog: "Health Pulse Blog",
    community: "NutriCircle Community",
    settings: "Settings",
    language: "App Language",
    notifications: "Smart Alerts",
    theme: "Dark Theme Mode",
    dailySummary: "Your Daily Health Summary",
    goals: "Your Fitness Goal",
    dietPreference: "Dietary Preference",
    calories: "Calories",
    protein: "Protein",
    carbs: "Carbs",
    fats: "Fats",
    waterTarget: "Daily Hydration Target",
    logWater: "Log Water Intake",
    medScheduled: "Medicines Today",
    addMed: "Add Medicine",
    weightLogged: "Weight Progress",
    logWeight: "Log Weight",
    kidsName: "Child's Name",
    currentWeek: "Current Week",
    symptoms: "Logged Symptoms",
    saveProfile: "Save Profile",
    enterDetails: "Enter Your Details",
    allergies: "Allergies / Restrictions",
    medicalHistory: "Medical Conditions",
    generatePlan: "Generate AI Plan",
    scanFood: "Scan Food Plate",
    uploadReport: "Upload Lab Report",
    chatWithDoc: "Chat with AI Doctor",
    referralCode: "Referral Code",
    applyCoupon: "Apply Coupon Code",
    successCoupon: "Coupon Applied Successfully!",
    referralBonus: "Invite friends and earn 500 NutriCoins!",
    offlineMode: "Offline Mode (Cached State)",
    syncPending: "Changes will sync when online"
  },
  hi: {
    appName: "न्यूट्रीओएस एआई",
    tagline: "भारत का हेल्थ सुपर ओएस",
    onboardingTitle: "एआई के साथ अपने स्वास्थ्य को बदलें",
    getStarted: "शुरू करें",
    login: "लॉगिन / साइन अप",
    logout: "लॉग आउट",
    welcome: "स्वागत है",
    streak: "लगातार दिन",
    days: "दिन",
    coins: "न्यूट्री कॉइन्स",
    premium: "प्रीमियम",
    buyPremium: "न्यूट्रीओएस गोल्ड में अपग्रेड करें",
    dashboard: "डैशबोर्ड",
    dietPlanner: "एआई डाइट प्लानर",
    groceryPlanner: "एआई राशन सूची",
    familyPlanner: "एआई परिवार पोषण",
    recipeGenerator: "एआई रेसिपी बिल्डर",
    restaurantHelper: "एआई रेस्टोरेंट हेल्पर",
    barcodeScanner: "एआई लेबल स्कैनर",
    foodCamera: "एआई फूड कैमरा",
    waterReminder: "एआई पानी ट्रैकर",
    medicineReminder: "एआई दवा अनुस्मारक",
    workoutPlan: "एआई कसरत योजना",
    labAnalyzer: "एआई लैब रिपोर्ट विशेषज्ञ",
    doctorChat: "एआई डॉक्टर चैट",
    kidsGrowth: "बच्चों का विकास",
    pregnancyTracker: "गर्भावस्था ट्रैकर",
    seniorCare: "वरिष्ठ नागरिक देखभाल",
    sleepTracker: "नींद और चक्र",
    weightTracker: "वजन और शरीर माप",
    subscription: "सदस्यता",
    affiliateMarket: "हेल्थ स्टोर",
    adminPanel: "कंट्रोल पैनल",
    blog: "हेल्थ ब्लॉग",
    community: "कम्युनिटी",
    settings: "सेटिंग्स",
    language: "ऐप की भाषा",
    notifications: "स्मार्ट नोटिफिकेशन",
    theme: "डार्क थीम",
    dailySummary: "आपका दैनिक स्वास्थ्य सारांश",
    goals: "आपका फिटनेस लक्ष्य",
    dietPreference: "आहार प्राथमिकता",
    calories: "कैलोरी",
    protein: "प्रोटीन",
    carbs: "कार्ब्स",
    fats: "वसा",
    waterTarget: "दैनिक जल लक्ष्य",
    logWater: "पानी दर्ज करें",
    medScheduled: "आज की दवाएं",
    addMed: "दवा जोड़ें",
    weightLogged: "वजन की प्रगति",
    logWeight: "वजन दर्ज करें",
    kidsName: "बच्चे का नाम",
    currentWeek: "वर्तमान सप्ताह",
    symptoms: "लक्षण",
    saveProfile: "प्रोफ़ाइल सहेजें",
    enterDetails: "विवरण दर्ज करें",
    allergies: "एलर्जी / प्रतिबंध",
    medicalHistory: "चिकित्सा स्थितियां",
    generatePlan: "एआई योजना बनाएं",
    scanFood: "भोजन स्कैन करें",
    uploadReport: "लैब रिपोर्ट अपलोड करें",
    chatWithDoc: "एआई डॉक्टर से बात करें",
    referralCode: "रेफरल कोड",
    applyCoupon: "कूपन कोड लागू करें",
    successCoupon: "कूपन सफलतापूर्वक लागू किया गया!",
    referralBonus: "दोस्तों को आमंत्रित करें और 500 कॉइन्स कमाएं!",
    offlineMode: "ऑफलाइन मोड (कैश डेटा)",
    syncPending: "ऑनलाइन होने पर बदलाव सिंक होंगे"
  },
  gu: {
    appName: "ન્યુટ્રીઓએસ એઆઈ",
    tagline: "ભારતનું હેલ્થ સુપર ઓએસ",
    onboardingTitle: "એઆઈ સાથે તમારા સ્વાસ્થ્યને બદલો",
    getStarted: "શરૂ કરો",
    login: "લોગિન / સાઇન અપ",
    logout: "લોગ આઉટ",
    welcome: "સ્વાગત છે",
    streak: "સતત દિવસો",
    days: "દિવસો",
    coins: "ન્યુટ્રી કોઈન્સ",
    premium: "પ્રીમિયમ",
    buyPremium: "ન્યુટ્રીઓએસ ગોલ્ડ મેળવો",
    dashboard: "ડેશબોર્ડ",
    dietPlanner: "એઆઈ ડાયેટ પ્લાનર",
    groceryPlanner: "એઆઈ કરિયાણા યાદી",
    familyPlanner: "એઆઈ ફેમિલી ન્યુટ્રિશન",
    recipeGenerator: "એઆઈ રેસીપી બિલ્ડર",
    restaurantHelper: "એઆઈ રેસ્ટોરન્ટ હેલ્પર",
    barcodeScanner: "એઆઈ લેબલ સ્કેનર",
    foodCamera: "એઆઈ ફૂડ કેમેરા",
    waterReminder: "એઆઈ પાણી ટ્રેકર",
    medicineReminder: "એઆઈ દવા રીમાઇન્ડર",
    workoutPlan: "એઆઈ ટ્રેનર કસરત",
    labAnalyzer: "એઆઈ લેબ રિપોર્ટ એક્સપર્ટ",
    doctorChat: "એઆઈ ડોક્ટર કન્સલ્ટન્ટ",
    kidsGrowth: "બાળક વિકાસ ટ્રેકર",
    pregnancyTracker: "ગર્ભાવસ્થા ટ્રેકર",
    seniorCare: "વડીલ કાળજી",
    sleepTracker: "ઊંઘ ટ્રેકર",
    weightTracker: "વજન અને બોડી માપ",
    subscription: "સબ્સ્ક્રિપ્શન",
    affiliateMarket: "હેલ્થ સ્ટોર",
    adminPanel: "કંટ્રોલ પેનલ",
    blog: "હેલ્થ બ્લોગ",
    community: "કોમ્યુનિટી",
    settings: "સેટિંગ્સ",
    language: "એપની ભાષા",
    notifications: "સ્માર્ટ એલર્ટ્સ",
    theme: "ડાર્ક થીમ",
    dailySummary: "દૈનિક હેલ્થ સારાંશ",
    goals: "ફિટનેસ લક્ષ્ય",
    dietPreference: "આહાર પ્રાધાન્ય",
    calories: "કેલરી",
    protein: "પ્રોટીન",
    carbs: "કાર્બોહાઇડ્રેટ",
    fats: "ચરબી",
    waterTarget: "પાણી પીવાનો લક્ષ્યાંક",
    logWater: "પાણી લોગ કરો",
    medScheduled: "આજની દવાઓ",
    addMed: "દવા ઉમેરો",
    weightLogged: "વજન પ્રગતિ",
    logWeight: "વજન લોગ કરો",
    kidsName: "બાળકનું નામ",
    currentWeek: "ચાલુ અઠવાડિયું",
    symptoms: "લક્ષણો",
    saveProfile: "પ્રોફાઇલ સાચવો",
    enterDetails: "માહિતી દાખલ કરો",
    allergies: "એલર્જી / પ્રતિકૂળતા",
    medicalHistory: "બીમારીઓ અને તકલીફો",
    generatePlan: "એઆઈ પ્લાન બનાવો",
    scanFood: "થાળી સ્કેન કરો",
    uploadReport: "રિપોર્ટ અપલોડ કરો",
    chatWithDoc: "એઆઈ ડોક્ટર સાથે ચેટ",
    referralCode: "રેફરલ કોડ",
    applyCoupon: "કૂપન કોડ ઉમેરો",
    successCoupon: "કૂપન સફળતાપૂર્વક લાગુ થઈ!",
    referralBonus: "મિત્રોને આમંત્રિત કરી 500 કોઈન્સ કમાઓ!",
    offlineMode: "ઓફલાઇન મોડ (સંગ્રહિત વિગતો)",
    syncPending: "ઓનલાઇન થતાં સિન્ક થશે"
  }
};

export const DEFAULT_PRODUCTS: MarketplaceProduct[] = [
  {
    id: "prod-1",
    name: "Premium Plant-Based Whey Protein (Rich Chocolate)",
    brand: "NutriOS Nutrition",
    category: "supplements",
    price: 1899,
    originalPrice: 2499,
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1579758629938-03607ccdbaba?q=80&w=300&auto=format&fit=crop",
    affiliateUrl: "https://amazon.in",
    description: "Formulated for superior absorption, delivering 25g premium pea and brown rice protein per serving. Perfect for lean muscle building and clean lifestyle integration."
  },
  {
    id: "prod-2",
    name: "Amla & Ashwagandha Revitalizing Immunity Gummies",
    brand: "Himalaya Wellness AI",
    category: "supplements",
    price: 499,
    originalPrice: 699,
    rating: 4.6,
    image: "https://images.unsplash.com/photo-1584017911766-d451b3d0e843?q=80&w=300&auto=format&fit=crop",
    affiliateUrl: "https://amazon.in",
    description: "Traditional Ayurvedic rejuvenative blends in a highly convenient chewable gummy format. Packed with Vitamin C and stress-relieving adaptogens."
  },
  {
    id: "prod-3",
    name: "Advanced Comprehensive 82-Parameter Full Body Health Checkup",
    brand: "Thyrocare Labs & NutriOS Diagnostics",
    category: "lab_tests",
    price: 1499,
    originalPrice: 3499,
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1579154204601-01588f351167?q=80&w=300&auto=format&fit=crop",
    affiliateUrl: "https://thyrocare.com",
    description: "Includes complete blood count, liver panels, kidney function profile, lipid profile, thyroid panel, and blood sugar indices. Free home sample collection."
  },
  {
    id: "prod-4",
    name: "Smart Bio-Sensor Fitness Ring (Slate Silver)",
    brand: "NutriOS Labs Wearables",
    category: "devices",
    price: 7999,
    originalPrice: 11999,
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1617038260897-41a1f14a8ca0?q=80&w=300&auto=format&fit=crop",
    affiliateUrl: "https://amazon.in",
    description: "Track your SpO2, sleep stages, continuous skin temperature patterns, and HRV trends with extreme accuracy. Seamless, automatic syncing to NutriOS."
  }
];

export const DEFAULT_BLOGS: BlogItem[] = [
  {
    id: "blog-1",
    title: "10 Powerful Superfoods and Spices native to Indian Kitchens",
    titleHi: "भारतीय रसोइयों में पाए जाने वाले 10 शक्तिशाली सुपरफूड और मसाले",
    titleGu: "ભારતીય રસોડામાં જોવા મળતા ૧૦ શક્તિશાળી સુપરફૂડ્સ અને મસાલાઓ",
    excerpt: "Discover the miraculous clinical advantages of turmeric, black pepper, amla, cumin and drumsticks.",
    excerptHi: "हल्दी, काली मिर्च, आंवला, जीरा और सहजन के चमत्कारी नैदानिक लाभों की खोज करें।",
    excerptGu: "હળદર, કાળા મરી, આમળા, જીરું અને સરગવાની સીંગોના ચમત્કારી ફાયદાઓ શોધો.",
    category: "Superfoods",
    image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?q=80&w=400&auto=format&fit=crop",
    readTime: "5 mins",
    content: "Indian kitchens are a treasure trove of clinical superfoods. Curcumin in turmeric has outstanding anti-inflammatory properties. Piperine in black pepper amplifies curcumin absorption by 2000%. Moringa (Drumsticks) has more Vitamin C than oranges and more calcium than milk. Incorporating these freshly ground spices daily promotes metabolic wellness, boosts gut flora and balances systemic inflammation."
  },
  {
    id: "blog-2",
    title: "Reversing Type-2 Diabetes through a Low-Carb Ayurvedic Lifestyle",
    titleHi: "कम कार्ब्स और आयुर्वेदिक जीवन शैली के माध्यम से टाइप-2 मधुमेह को उलटना",
    titleGu: "લો-કાર્બ અને આયુર્વેદિક જીવનશૈલી દ્વારા ટાઇપ-૨ ડાયાબિટીસને મટાડવો",
    excerpt: "How balancing meal composition and simple herbs can lead to clinically sustained HbA1c reductions.",
    excerptHi: "भोजन की संरचना और सरल जड़ी-बूटियों को संतुलित करके आप अपने HbA1c स्तर को कम कर सकते हैं।",
    excerptGu: "ખોરાકની ગુણવત્તા અને આયુર્વેદિક જડીબુટ્ટીઓના સંતુલનથી HbA1c ઘટાડો મેળવી શકાય છે.",
    category: "Metabolism",
    image: "https://images.unsplash.com/photo-1490645935967-10de6ba17061?q=80&w=400&auto=format&fit=crop",
    readTime: "8 mins",
    content: "Clinically structured type-2 diabetes reversal centers around carb restriction and metabolic enhancement. By substituting high-GI grains like polished white rice with finger millet (ragi), sorghum (jowar), or quinoa, insulin spikes are mitigated. Integrating ayurvedic adaptogens like Bitter Melon (Karela), Jamun seeds, and Fenugreek (Methi) helps improve pancreatic cell health and peripheral insulin sensitivity."
  }
];

export const DEFAULT_COMMUNITY: CommunityPost[] = [
  {
    id: "post-1",
    author: "Rohan Sharma, Mumbai",
    authorGoal: "Weight Loss Goal Accomplished",
    content: "Down 12 kgs in 3 months! All thanks to NutriOS AI's low-carb Jain meal plans. The custom protein targets were super easy to achieve with sprouted dals and paneer.",
    likes: 42,
    likedByMe: false,
    comments: [
      { author: "Sneha Patel", text: "Incredible transformation Rohan! Inspiring me to log my meals too.", date: "2026-07-18" },
      { author: "Amit Trivedi", text: "Did you use any protein supplements or pure diet?", date: "2026-07-19" }
    ],
    date: "2026-07-18T10:30:00Z"
  },
  {
    id: "post-2",
    author: "Dr. Anjali Mehta, Bengaluru",
    authorGoal: "Clinical Sports Nutritionist",
    content: "Reminder to all premium NutriOS users: Always upload your blood reports before requesting an AI diet plan update. The AI reads thyroid (TSH) and vitamin profiles to calibrate energy levels perfectly!",
    likes: 89,
    likedByMe: true,
    comments: [],
    date: "2026-07-19T08:15:00Z"
  }
];

export const MOCK_RECIPE_SUGGESTIONS = [
  {
    name: "High Protein Palak Paneer",
    calories: 320,
    protein: 22,
    carbs: 12,
    fats: 18,
    ingredients: ["Paneer", "Spinach", "Garlic", "Ginger", "Green Chili", "Cumin seeds", "Tomato", "Greek Yogurt"],
    steps: [
      "Blanch spinach in boiling water for 2 minutes, then shock in cold water and blend with green chilies.",
      "Sauté chopped garlic, ginger, and cumin seeds in a teaspoon of olive oil.",
      "Add pureed spinach, diced paneer cubes, and spices (turmeric, coriander powder, salt).",
      "Stir in a dollop of Greek yogurt for extra creamy texture and proteins. Simmer for 5 mins."
    ]
  },
  {
    name: "Sprouted Moong Khichdi (Low Carb)",
    calories: 280,
    protein: 16,
    carbs: 38,
    fats: 6,
    ingredients: ["Sprouted Moong", "Brown Rice", "Ghee", "Asafoetida (Hing)", "Turmeric", "Onion", "Tomato", "Curry Leaves"],
    steps: [
      "Wash sprouted moong and brown rice in a 2:1 ratio.",
      "In a pressure cooker, heat a teaspoon of cow ghee. Add mustard seeds, curry leaves, and a pinch of hing.",
      "Add finely chopped onion and tomatoes, sautéing until soft.",
      "Add sprouted moong, rice, turmeric, salt, and water. Pressure cook for 3 whistles until soft and mushy."
    ]
  }
];

export const WORKOUT_EXERCISES = {
  weight_loss: [
    { name: "Jumping Jacks", duration: "60 seconds", description: "High tempo cardio to trigger fat oxidation" },
    { name: "Bodyweight Squats", duration: "15 reps x 3 sets", description: "Builds leg muscle and burns sustained calories" },
    { name: "High Knees", duration: "45 seconds", description: "Intense core-centric aerobic movement" }
  ],
  muscle_building: [
    { name: "Push-ups (Standard/Incline)", duration: "12 reps x 3 sets", description: "Targeting chest, front deltoids, and triceps" },
    { name: "Dumbbell/Backpack Rows", duration: "15 reps x 3 sets", description: "Strengthening latissimus dorsi and rhomboids" },
    { name: "Plank holds", duration: "60 seconds", description: "Static core abdominal strength builder" }
  ],
  general_fitness: [
    { name: "Surya Namaskar (Sun Salutations)", duration: "5 rounds", description: "Ancient systemic flexibility and dynamic stretching" },
    { name: "Bird-Dog", duration: "10 reps each side", description: "Spinal stability and glute strength balance" },
    { name: "Brisk Walking on Spot", duration: "5 minutes", description: "Low-impact metabolic system primer" }
  ]
};
